import type { Module } from '../storage/types';

export const DEFAULT_MODULES: Module[] = [
  {
    id: 'mod-interview-prep',
    name: 'Interview Preparation',
    family: 'Interview & Executive Readiness',
    type: 'native',
    status: 'active',
  },
  {
    id: 'mod-b2b-sales',
    name: 'Strategic & Complex B2B Sales Fluency',
    family: 'Sales Fluency',
    type: 'light',
    contentRef: 'b2b-sales',
    status: 'pending',
  },
  {
    id: 'mod-clevel-qs',
    name: 'C-Level Questioning & Prompting',
    family: 'Sales Fluency',
    type: 'light',
    contentRef: 'clevel-qs',
    status: 'active',
  },
  {
    id: 'mod-exec-presence',
    name: 'Executive Presence',
    family: 'Interview & Executive Readiness',
    type: 'light',
    contentRef: 'exec-presence',
    status: 'active',
  },
  {
    id: 'mod-banking-insurance',
    name: 'Banking & Insurance Fluency',
    family: 'Industry Expertise',
    type: 'light',
    contentRef: 'banking-insurance',
    status: 'pending',
  },
  {
    id: 'mod-leadership',
    name: 'Leadership Expertise',
    family: 'Leadership & Management',
    type: 'light',
    contentRef: 'leadership',
    status: 'pending',
  },
  {
    id: 'mod-management',
    name: 'Management Philosophy',
    family: 'Leadership & Management',
    type: 'light',
    contentRef: 'management',
    status: 'pending',
  },
  {
    id: 'mod-thought-leadership',
    name: 'Thought Leadership in Agentic AI',
    family: 'Thought Leadership / LinkedIn',
    type: 'light',
    contentRef: 'agentic-thought',
    cadence: { frequency: 'weekly', durationMin: 60 },
    status: 'pending',
  },
  {
    id: 'mod-linkedin',
    name: 'LinkedIn Profile & Resume',
    family: 'Thought Leadership / LinkedIn',
    type: 'external',
    contentRef: 'linkedin-profile',
    status: 'pending',
  },
  {
    id: 'mod-ai-cert',
    name: 'AI Certification Track',
    family: 'Certifications',
    type: 'generator',
    cadence: { frequency: 'weekly', preferredDay: 'Tuesday', durationMin: 120 },
    status: 'active',
  },
  {
    id: 'mod-reading',
    name: 'Reading & Viewing',
    family: 'Knowledge Intake',
    type: 'light',
    contentRef: 'reading-queue',
    status: 'active',
  },
  {
    id: 'mod-podcasts',
    name: 'Podcasts',
    family: 'Knowledge Intake',
    type: 'generator',
    cadence: { frequency: 'weekly', durationMin: 60 },
    status: 'active',
  },
  {
    id: 'mod-agentic-expert',
    name: 'Agentic AI Expert',
    family: 'Agentic AI Expertise',
    type: 'light',
    contentRef: 'agentic-expert',
    status: 'pending',
  },
  {
    id: 'mod-agentic-cx',
    name: 'Agentic AI for Customer Engagement',
    family: 'Agentic AI Expertise',
    type: 'light',
    contentRef: 'agentic-cx',
    status: 'pending',
  }
];
